watch_stylesheet: true
watch_config: true
debug: false
bars:
  status-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    animation:
      enabled: true
      duration: 800
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: true
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 40
    widgets:
      left: ["home", "wallpaper", "cpu", "memory", "disk", "media"]
      center: ["active_window"]
      right:
        ["weather", "clock", "volume", "wifi", "notifications", "power_menu"]
widgets:
  pomodoro:
    type: "yasb.pomodoro.PomodoroWidget"
    options:
      label: "<span>{icon}</span> {remaining}"
      label_alt: "<span>{icon}</span> {session}/{total_sessions} - {status}"
      work_duration: 30
      break_duration: 5
      long_break_duration: 5
      long_break_interval: 4
      auto_start_breaks: false
      auto_start_work: false
      sound_notification: true
      show_notification: true
      hide_on_break: false
      session_target: 8
      icons:
        work: "\uf252"
        break: "\uf253"
        paused: "\uf254"
      menu:
        alignment: "right"
        direction: "down"
        circle_background_color: "#09ffffff"
        circle_work_progress_color: "#88c0d0"
        circle_break_progress_color: "#a3be8c"
        circle_thickness: 8
        circle_size: 160
      callbacks:
        on_left: "toggle_menu"
        on_middle: "reset_timer"
        on_right: "toggle_label"
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>\uf476</span> {count}"
      label_alt: "{count} Notifications"
      hide_empty: false
      tooltip: true
      callbacks:
        on_left: "toggle_notification"
        on_right: "do_nothing"
        on_middle: "toggle_label"
  wallpaper:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<span>\uf03e</span>"
      image_path: "C:\\Users\\maity\\Pictures\\Wallpapers"
      change_automatically: false # Automatically change wallpaper
      update_interval: 60
      gallery:
        enabled: true
        image_width: 250
        image_per_page: 4
        show_buttons: true
        orientation: "portrait"
        image_spacing: 15
        lazy_load: true
        lazy_load_delay: 80
        lazy_load_fadein: 400
        image_corner_radius: 8
        enable_cache: true
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\udb80\udf5c</span>"
      menu_list:
        - { title: "Downloads", path: "C:\\Users\\maity\\Downloads" }
        - { title: "Documents", path: "C:\\Users\\maity\\Documents" }
        - { title: "Pictures", path: "C:\\Users\\maity\\Pictures" }
        - { title: "Videos", path: "C:\\Users\\maity\\Videos" }
      system_menu: true
      power_menu: false
      distance: 10
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "<span>\udb80\udf87</span> {title}"
      label_alt: "<span>\udb80\udf87</span> {artist}"
      hide_empty: true
      callbacks:
        on_left: "toggle_media_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      max_field_size:
        label: 30
        label_alt: 30
      show_thumbnail: false
      controls_only: false
      controls_left: true
      thumbnail_alpha: 50
      thumbnail_padding: 0
      thumbnail_corner_radius: 8
      icons:
        play: "\uf04b"
        pause: "\uf04c"
      media_menu:
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        show_source: true
        show_volume_slider: true
      media_menu_icons:
        play: "\ue768"
        pause: "\ue769"
        prev_track: "\ue892"
        next_track: "\ue893"
        mute: "\ue994"
        unmute: "\ue74f"
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "<span>{icon}</span> {%I:%M:%S %p}"
      label_alt: "\uf017 {%d-%m-%y | %A}"
      locale: ""
      update_interval: 1000
      timezones: []
      icons:
        clock_01: "\udb85\udc3f"
        clock_02: "\udb85\udc40"
        clock_03: "\udb85\udc41"
        clock_04: "\udb85\udc42"
        clock_05: "\udb85\udc43"
        clock_06: "\udb85\udc44"
        clock_07: "\udb85\udc45"
        clock_08: "\udb85\udc46"
        clock_09: "\udb85\udc47"
        clock_10: "\udb85\udc48"
        clock_11: "\udb85\udc49"
        clock_12: "\udb85\udc4a"
        clock_16: "SNACK TIME !"
        clock_21: "Zzz..."
        clock_22: "Zzz..."
        clock_23: "Zzz..."
      calendar:
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
        show_holidays: false
        show_week_numbers: true
        country_code: "AR"
        holiday_color: "#FF6464"
      callbacks:
        on_left: "toggle_label"
        on_right: "toggle_calendar"
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "{location}: {conditions}, Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: "7bb1bda2442a452aa8e151728242809"
      update_interval: 600 #Update interval in seconds, Min 600
      hide_decimal: true
      location: "Kolkata, IN"
      units: "metric"
      callbacks:
        on_left: "toggle_card"
      icons:
        sunnyDay: "\ue30d"
        clearNight: "\ue32b"
        cloudyDay: "\ue312"
        cloudyNight: "\ue311"
        rainyDay: "\ue308"
        rainyNight: "\ue333"
        snowyIcyDay: "\ue30a"
        snowyIcyNight: "\ue335"
        blizzardDay: "\udb83\udf36"
        blizzardNight: "\udb83\udf36"
        foggyDay: "\ue303"
        foggyNight: "\ue346"
        thunderstormDay: "\ue30f"
        thunderstormNight: "\ue338"
        default: "\uebaa"
      weather_card:
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "right"
        direction: "down"
        icon_size: 64
        show_hourly_forecast: true
        time_format: "12h"
        hourly_point_spacing: 76
        hourly_icon_size: 32
        icon_smoothing: true
        temp_line_width: 2
        current_line_color: "#8EAEE8"
        current_line_width: 1
        current_line_style: "dot"
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8"
        - "\uf026"
        - "\uf027"
        - "\uf027"
        - "\uf028"
      audio_menu:
        alignment: "center"
        direction: "down"
      callbacks:
        on_left: "toggle_volume_menu"
        on_middle: "toggle_mute"
        on_right: "exec quick_settings"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: true
      animation_duration: 250
      button_row: 3
      buttons:
        signout: ["\udb80\udf43", "Sign out"]
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        sleep: ["\udb82\udd04", "Sleep"]
        lock: ["\uf023", "Lock"]
        cancel: ["\udb81\udf3a", "Cancel"]
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: ""
      label_alt: "{win[title]}"
      label_no_window: ""
      label_icon: true
      label_icon_size: 14
      max_length: 14
      max_length_ellipsis: "..."
      monitor_exclusive: true
      rewrite:
        - pattern: "^(.+?)\\.exe$"
          replacement: "\\1"
          case: capitalize
  disk:
    type: "yasb.disk.DiskWidget"
    options:
      label: "<span>\uf473</span>"
      label_alt: "<span>\uf473</span>"
      group_label:
        volume_labels: ["C", "D", "E", "F"]
        show_label_name: true
        alignment: "right"
        direction: "down"
        distance: 6
      callbacks:
        on_left: "toggle_group"
        on_right: "exec explorer.exe"
      progress_bar:
        enabled: true
        thickness: 2
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]} %"
      label_alt: "<span>\uf437</span> {info[histograms][cores]}"
      update_interval: 2000
      cpu_thresholds:
        low: 25
        medium: 50
        high: 90
      histogram_icons:
        - "\u2581" # 0%
        - "\u2581" # 10%
        - "\u2582" # 20%
        - "\u2583" # 30%
        - "\u2584" # 40%
        - "\u2585" # 50%
        - "\u2586" # 60%
        - "\u2587" # 70%
        - "\u2588" # 80%+
      histogram_num_columns: 16
      callbacks:
        on_right: "exec cmd /c Taskmgr"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      progress_bar:
        enabled: true
        thickness: 2
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uefc5</span> {virtual_mem_percent} %"
      label_alt: "<span>\uefc5</span> {virtual_mem_used}/{virtual_mem_total}"
      update_interval: 5000
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      memory_thresholds:
        low: 25
        medium: 50
        high: 90
      histogram_icons:
        - "\u2581" # 0%
        - "\u2581" # 10%
        - "\u2582" # 20%
        - "\u2583" # 30%
        - "\u2584" # 40%
        - "\u2585" # 50%
        - "\u2586" # 60%
        - "\u2587" # 70%
        - "\u2588" # 80%+
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      progress_bar:
        enabled: true
        thickness: 2
  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span>{wifi_icon}</span>"
      label_alt: "{wifi_name} {wifi_strength}%"
      update_interval: 5000
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      wifi_icons:
        [
          "\udb82\udd2e",
          "\udb82\udd1f",
          "\udb82\udd22",
          "\udb82\udd25",
          "\udb82\udd28",
        ]
